# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:26:08+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic

from models import (
    FullComparisonTest,
    ScreenshotsTargetScreenshotTestIdTargetVersionIdComparisonParallelBaseVersionIdGetResponse,
    SingleComparisonTest,
)

app = MCPProxy(
    contact={'x-twitter': 'xbrowsertesting'},
    description="What's in this version: \n 1. Compare two screenshots for layout differences \n 2. Compare a full screenshot test of browsers to a single baseline browser for layout differences. \n 3. Compare a screenshot test version to another test version - good for regression tests. \n 4. Get links to the Comparison UI for visual representation of layout differences",
    title='Crossbrowsertesting.com Screenshot Comparisons API',
    version='3.0.0',
    servers=[{'url': 'https://crossbrowsertesting.com/api/v3'}],
)


@app.get(
    '/screenshots/{target_screenshot_test_id}/{target_version_id}/comparison/parallel/{base_version_id}',
    description=""" Get comparison results for all browsers in target screenshot test against the same browser in the base screenshot test. This is a good method for regression testing. For example, you've run a screenshot test against a set of browsers that is "good". Then, after some changes, you run a new screenshot test against the same set of browsers. This method will compare each of the same browsers against each other. For example, IE9 will be compared to IE9 from an earlier test. This is a many-to-many comparison where the OS/Browser/Resolution must match between the two test versions in order for the comparison to return results. The two versions can be from the same screenshot_test_id or not. """,
    tags=['screenshot_version_comparison'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def compare_screenshot_test_versions(
    target_screenshot_test_id: int,
    target_version_id: int = ...,
    base_version_id: int = ...,
    format: Optional[str] = 'json',
    callback: Optional[str] = None,
    tolerance: Optional[float] = 30,
):
    """
    Compare Screenshot Test Versions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/screenshots/{target_screenshot_test_id}/{target_version_id}/comparison/{base_result_id}',
    description=""" Get comparison results for all browsers in target screenshot test against a base screenshot result. The base result can be from the same test or from another test run at an earlier time. This is a one-to-many comparison. """,
    tags=['screenshot_version_comparison'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def compare_full_screenshot_test(
    target_screenshot_test_id: int,
    target_version_id: int = ...,
    base_result_id: int = ...,
    format: Optional[str] = 'json',
    callback: Optional[str] = None,
    tolerance: Optional[float] = 30,
):
    """
    Compare Full Screenshot Test
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/screenshots/{target_screenshot_test_id}/{target_version_id}/{target_result_id}/comparison/{base_result_id}',
    description=""" Get comparison results for a single target screenshot result against a base screenshot result. This is a one-to-one comparison. """,
    tags=['screenshot_version_comparison'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def compare_single_screenshot(
    target_screenshot_test_id: int,
    target_version_id: int = ...,
    target_result_id: int = ...,
    base_result_id: int = ...,
    format: Optional[str] = 'json',
    callback: Optional[str] = None,
    tolerance: Optional[float] = 30,
):
    """
    Compare Single Screenshot
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
