# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:26:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class Element(BaseModel):
    difference: Optional[str] = None
    full_path: Optional[str] = None
    short_path: Optional[str] = None
    show_difference_public_url: Optional[str] = None
    show_difference_web_url: Optional[str] = None


class Screenshot(BaseModel):
    screenshot_id: Optional[int] = None


class Base(BaseModel):
    screenshot: Optional[Screenshot] = None


class Comparison(BaseModel):
    differences: Optional[int] = None
    elements: Optional[List[Element]] = None
    error: Optional[bool] = None
    message: Optional[str] = None
    show_comparisons_public_url: Optional[str] = None
    show_comparisons_web_url: Optional[str] = None
    tolerance: Optional[int] = None


class Target(BaseModel):
    comparison: Optional[Comparison] = None
    screenshot: Optional[Screenshot] = None


class FullComparisonTest(BaseModel):
    base: Optional[Base] = None
    targets: Optional[List[Target]] = None


class SingleComparisonTest(BaseModel):
    base: Optional[Base] = None
    target: Optional[Target] = None


class ScreenshotsTargetScreenshotTestIdTargetVersionIdComparisonParallelBaseVersionIdGetResponse(
    RootModel[List[SingleComparisonTest]]
):
    root: List[SingleComparisonTest]
